name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      twitter_token: ${{ steps.post-to-x.outputs.TWITTER_REFRESH_TOKEN }}
      token_updated: ${{ steps.check-token.outputs.token_updated }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build site with Twitter posting
        id: post-to-x
        env:
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_REFRESH_TOKEN: ${{ secrets.TWITTER_REFRESH_TOKEN }}
        run: |
          npm run build
          # If a new token was generated, read it and set as output
          if [ -f "twitter_tokens/new_refresh_token.txt" ]; then
            echo "TWITTER_REFRESH_TOKEN<<EOF" >> $GITHUB_OUTPUT
            cat twitter_tokens/new_refresh_token.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      
      - name: Check if token was updated
        id: check-token
        run: |
          if [ -f "twitter_tokens/new_refresh_token.txt" ]; then
            echo "token_updated=true" >> $GITHUB_OUTPUT
          else
            echo "token_updated=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  update-token:
    needs: build
    if: needs.build.outputs.token_updated == 'true'
    uses: ./.github/workflows/store-twitter-token.yml
    with:
      token: ${{ needs.build.outputs.twitter_token }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}