name: Build and Deploy

# THIS WORKFLOW IS DEPRECATED
# Please use consolidated-workflow.yml instead
# This file is kept for reference only and will be removed in the future
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated Workflow
        run: |
          echo "This workflow is deprecated. Please use consolidated-workflow.yml instead."
          exit 1